apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    appname: busybox
  name: ${DEPLOYMENT_NAME}-pvc
  namespace: ${NAMESPACE}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ${STORAGECLASS}
